/**
 * @copyright Copyright (C) REALTECH AG, Germany - All Rights Reserved
 *  Unauthorized copying of this file, via any medium is strictly prohibited
 *  Proprietary and confidential
 *  Written by Tobias Ceska <tobias.ceska@realtech.com>, December 2019
 */

userinfo = {
  id: 1,
  email: 'user@email.de',
  culture: 'en-US',
  firstName: 'User Firstname',
  lastName: 'User Lastname',
  description: 'Description of the User',
  lastLogin: '2019-02-07T07:52:58.53Z',

  password: '',
  person: {
    hasUserAccount: true,
    userId: 1,
    email: 'admin@realtech.de',
    description: 'Administrator  dededek',
    lastName: 'Hammer',
    firstName: 'Ober',
    timeZone: 'UTC',
    culture: 'en-US',
    autoName: 'OR-PERS-3',
    lifecyclePhase: null,
    lifecycleStatus: null,
    autoNumber: null,
    ciTypeId: 137,
    ciTypeUuid: 'b5060d56-475a-4d99-9aec-edf86d8b4df3',
    ciTypeName: 'Person',
    ciTypePath: null,
    lifecyclePhaseName: null,
    lifecycleStatusName: null,
    lifecycleStatusClass: 0,
    assetNumber: null,
    dynamicProperties: {
      description: 'Administrator  dededek',
      email_PERS: 'admin@realtech.de',
      firstName_PERS: 'Ober',
      lastName_PERS: 'Hammer',
      position_PERS: [],
      personnelNumber_PERS: '',
      telephoneNumbersBusiness_PERS: [''],
      faxBusiness_PERS: '',
      mobilePhoneNumbersBusiness_PERS: [''],
      weblinks_PERS: [''],
      personnelCosts_PERS: [],
      language_PERS: 'en-US',
      timeZone_PERS: 'UTC',
      userId_PERS: 1,
      userExisting_PERS: true,
      department_PERS: null,
      supervisor_PERS: null,
      substitution_PERS: null,
      room_PERS: null,
      company_PERS: null
    },
    id: 1,
    uuid: '30383968-96f3-4a3a-8920-18d2ffdc5126',
    imageId: 17,
    name: 'Ober Hammer',
    upcomingAutoNumberOverflow: false,
    version: null,
    createdBy: 0,
    createdByUser: null,
    creationDate: '2017-05-03T10:06:59.947Z',
    modifiedBy: 1,
    modifiedByUser: 'Ober Hammer',
    modificationDate: '2019-01-11T12:59:30.727Z',
    comparisonDate: null,
    note: null,
    isDeactivated: false,
    noPrivilegeVersion: false
  },
  timeZone: 'UTC',
  uuid: '1a18a13c-b0fc-4251-b8d0-6b5a91d6243b',
  windowsLogin: '',
  hasOperatorLicense: true
};
